### ISSUE TITLE
Cannot use ImageField because Pillow is not installed

### ISSUE THREAD

**Issue by natget21** [linuxserver/docker-netbox#37]
while using the image lscr.io/linuxserver/netbox:latest  on docker raspberry pi 4 net box failed to start  with the following log error output

cpu archtecture -> arm64
image.version ->  v3.2.5-ls75

deployed with docker-compose file
```
version: "2.1"
services:
  netbox:
    image: lscr.io/linuxserver/netbox:latest
    container_name: netbox
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Europe/Rome
      - SUPERUSER_EMAIL=********
      - SUPERUSER_PASSWORD=*******
      - ALLOWED_HOST=192.168.*.*
      - DB_NAME=netbox
      - DB_USER=postgres
      - DB_PASSWORD=******
      - DB_HOST=192.168.*.*
      - DB_PORT=5432
      - REDIS_HOST=192.168.*.*
      - REDIS_PORT=6379
      - REDIS_PASSWORD=*************
      - REDIS_DB_TASK=0
      - REDIS_DB_CACHE=1
     #      - BASE_PATH=<BASE_PATH> #optional
     #      - REMOTE_AUTH_ENABLED=<REMOTE_AUTH_ENABLED> #optional
     #      - REMOTE_AUTH_BACKEND=<REMOTE_AUTH_BACKEND> #optional
     #      - REMOTE_AUTH_HEADER=<REMOTE_AUTH_HEADER> #optional
     #      - REMOTE_AUTH_AUTO_CREATE_USER=<REMOTE_AUTH_AUTO_CREATE_USER> #optional
     #      - REMOTE_AUTH_DEFAULT_GROUPS=<REMOTE_AUTH_DEFAULT_GROUPS> #optional
     #      - REMOTE_AUTH_DEFAULT_PERMISSIONS=<REMOTE_AUTH_DEFAULT_PERMISSIONS> #optional
    volumes:
      - netbox_data:/config
    ports:
      - 8000:8000
    restart: unless-stopped
volumes:
    netbox_data:
        external: true
```

ERROR LOG Output
```
running "exec:/usr/bin/python3 ./manage.py remove_stale_contenttypes --no-input" (pre app)...
SystemCheckError: System check identified some issues:
ERRORS:
dcim.DeviceType.front_image: (fields.E210) Cannot use ImageField because Pillow is not installed.
	HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
dcim.DeviceType.rear_image: (fields.E210) Cannot use ImageField because Pillow is not installed.
	HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
extras.ImageAttachment.image: (fields.E210) Cannot use ImageField because Pillow is not installed.
	HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
command "/usr/bin/python3 ./manage.py remove_stale_contenttypes --no-input" exited with non-zero code: 1
Wed Jul 13 01:08:59 2022 - FATAL hook failed, destroying instance
SIGINT/SIGQUIT received...killing workers...
WSGI app 0 (mountpoint='') ready in 8 seconds on interpreter 0xffffb99c4b20 pid: 315 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 315)
spawned uWSGI worker 1 (pid: 334, cores: 1)
[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py rqworker" (uid: 1000 gid: 1003)
SystemCheckError: System check identified some issues:
ERRORS:
dcim.DeviceType.front_image: (fields.E210) Cannot use ImageField because Pillow is not installed.
	HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
dcim.DeviceType.rear_image: (fields.E210) Cannot use ImageField because Pillow is not installed.
	HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
extras.ImageAttachment.image: (fields.E210) Cannot use ImageField because Pillow is not installed.
	HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
daemon "/usr/bin/python3 ./manage.py rqworker" (pid: 335) annihilated
```
